AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda function triggered on a schedule that queries the Twitter API.

Globals:
  Function:
    Timeout: 30

Resources:
  QueryTwitterApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: function/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: "rate(1 minute)"
            Enabled: false # Change to `true` to activate schedule.
