AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda function triggered on a schedule that queries the Twitter API.

Globals:
  Function:
    Timeout: 30

Resources:
  QueryTwitterApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: search_api/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          CONSUMER_KEY: "{{resolve:secretsmanager:twitter-consumer-key:SecretString}}"
          CONSUMER_SECRET: "{{resolve:secretsmanager:twitter-consumer-secret:SecretString}}"
          QUERY: "kd OR Ebba Busch OR kristdemokraterna"
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: "rate(1 minute)"
            Enabled: true # Change to `true` to activate schedule.
      Tags:
        project: twitter
        service: query-api
